import {
	createAgent,
	createNetwork,
	createState,
	type Message,
	openai,
} from "@inngest/agent-kit";
import { createImprovementPrompt } from "./helpers/prompts/improvement";
import { createPlanningPrompt } from "./helpers/prompts/planning";
import { createReviewPrompt } from "./helpers/prompts/review";
import { createWritingPrompt } from "./helpers/prompts/writing";
import { formatDuration, getTextContent, parseJSON } from "./helpers/utils";
import type {
	AgentTiming,
	FinalDocument,
	WritingAgentState,
	WritingDraft,
	WritingPlan,
	WritingReview,
} from "./types";

const groqConfig = {
	apiKey: process.env.GROQ_API_KEY,
	baseUrl: process.env.GROQ_BASE_URL || "https://api.groq.com/openai/v1/",
};

const planningAgent = createAgent<WritingAgentState>({
	name: "Planning Agent",
	system: createPlanningPrompt(),
	model: openai({
		model: "openai/gpt-oss-safeguard-20b",
		...groqConfig,
	}),
	lifecycle: {
		onStart: ({ prompt, history, network }) => {
			const state = network?.state.data as WritingAgentState;
			state._agentStartTimes["Planning Agent"] = Date.now();
			return { prompt, history: history || [], stop: false };
		},
		onFinish: ({ result, network }) => {
			const state = network?.state.data as WritingAgentState;
			const startTime = state._agentStartTimes["Planning Agent"];
			if (startTime) {
				state.timings.push({
					name: "Planning Agent",
					duration: Date.now() - startTime,
				});
			}
			return result;
		},
	},
});

const writerAgent = createAgent<WritingAgentState>({
	name: "Writing Agent",
	system: ({ network }) => {
		const state = network?.state.data as WritingAgentState;
		if (!state.plan) return "Awaiting plan...";
		return createWritingPrompt(state.plan);
	},
	model: openai({
		model: "groq/compound",
		...groqConfig,
	}),
	lifecycle: {
		onStart: ({ prompt, history, network }) => {
			const state = network?.state.data as WritingAgentState;
			state._agentStartTimes["Writing Agent"] = Date.now();
			const planMessage: Message = {
				type: "text",
				role: "user",
				content:
					"Here is the writing plan generated by the Planning Agent. Now write the draft based on this plan.",
			};
			return {
				prompt,
				history: [...(history || []), planMessage],
				stop: false,
			};
		},
		onFinish: ({ result, network }) => {
			const state = network?.state.data as WritingAgentState;
			const startTime = state._agentStartTimes["Writing Agent"];
			if (startTime) {
				state.timings.push({
					name: "Writing Agent",
					duration: Date.now() - startTime,
				});
			}
			return result;
		},
	},
});

const reviewAgent = createAgent<WritingAgentState>({
	name: "Review Agent",
	system: ({ network }) => {
		const state = network?.state.data as WritingAgentState;
		if (!state.plan || !state.draft) return "Awaiting plan and draft...";
		return createReviewPrompt(state.plan, state.draft);
	},
	model: openai({
		model: "openai/gpt-oss-20b",
		...groqConfig,
	}),
	lifecycle: {
		onStart: ({ prompt, history, network }) => {
			const state = network?.state.data as WritingAgentState;
			state._agentStartTimes["Review Agent"] = Date.now();
			const draftMessage: Message = {
				type: "text",
				role: "user",
				content:
					"Here is the draft generated by the Writing Agent. Please review it against the original plan and provide feedback",
			};
			return {
				prompt,
				history: [...(history || []), draftMessage],
				stop: false,
			};
		},
		onFinish: ({ result, network }) => {
			const state = network?.state.data as WritingAgentState;
			const startTime = state._agentStartTimes["Review Agent"];
			if (startTime) {
				state.timings.push({
					name: "Review Agent",
					duration: Date.now() - startTime,
				});
			}
			return result;
		},
	},
});

const improvementAgent = createAgent<WritingAgentState>({
	name: "Improvement Agent",
	system: ({ network }) => {
		const state = network?.state.data as WritingAgentState;
		if (!state.plan || !state.draft || !state.review) {
			return "Awaiting plan, draft, and review...";
		}
		return createImprovementPrompt(state.plan, state.draft, state.review);
	},
	model: openai({
		model: "moonshotai/kimi-k2-instruct-0905",
		...groqConfig,
	}),
	lifecycle: {
		onStart: ({ prompt, history, network }) => {
			const state = network?.state.data as WritingAgentState;
			state._agentStartTimes["Improvement Agent"] = Date.now();
			const reviewMessage: Message = {
				type: "text",
				role: "user",
				content:
					"Here is the review feedback from the Review Agent. Please improve the draft based on the feedback.\n\nNow improve the draft and produce the final document.",
			};
			return {
				prompt,
				history: [...(history || []), reviewMessage],
				stop: false,
			};
		},
		onFinish: ({ result, network }) => {
			const state = network?.state.data as WritingAgentState;
			const startTime = state._agentStartTimes["Improvement Agent"];
			if (startTime) {
				state.timings.push({
					name: "Improvement Agent",
					duration: Date.now() - startTime,
				});
			}
			return result;
		},
	},
});

const agents = [planningAgent, writerAgent, reviewAgent, improvementAgent];

const router = async ({
	network,
	callCount,
	lastResult,
}: {
	network: { state: { data: WritingAgentState } };
	callCount: number;
	lastResult?: { output: Message[] };
}) => {
	const state = network.state.data;

	if (lastResult?.output) {
		const text = getTextContent(lastResult.output);

		switch (callCount) {
			case 1: {
				const plan = parseJSON<WritingPlan>(text);
				if (plan) network.state.data.plan = plan;
				break;
			}
			case 2: {
				const result = parseJSON<WritingDraft>(text);
				if (result?.draft) network.state.data.draft = result.draft;
				break;
			}
			case 3: {
				const review = parseJSON<WritingReview>(text);
				if (review) network.state.data.review = review;
				break;
			}
			case 4: {
				const final = parseJSON<FinalDocument>(text);
				if (final?.final_document) {
					network.state.data.finalDocument = final.final_document;
				}
				break;
			}
		}
	}

	if (callCount === 0) return planningAgent;
	if (callCount === 1 && state.plan) return writerAgent;
	if (callCount === 2 && state.draft) return reviewAgent;
	if (callCount === 3 && state.review) return improvementAgent;

	return undefined;
};

export const writingNetwork = createNetwork<WritingAgentState>({
	name: "Writing Agent Network",
	agents,
	defaultModel: openai({
		model: "llama-3.3-70b-versatile",
		...groqConfig,
	}),
	maxIter: 10,
	router,
});

export interface OrchestratorResult {
	success: boolean;
	finalDocument?: string;
	state: WritingAgentState;
	timings: AgentTiming[];
	totalDuration: number;
}

export async function runWritingWorkflow(
	userPrompt: string,
): Promise<OrchestratorResult> {
	const totalStart = Date.now();

	const state = createState<WritingAgentState>({
		userPrompt,
		timings: [],
		_agentStartTimes: {},
	});

	console.log("[START] Writing workflow");

	await writingNetwork.run(userPrompt, { state });

	const totalDuration = Date.now() - totalStart;

	for (const timing of state.data.timings) {
		console.log(`[DONE] ${timing.name} (${formatDuration(timing.duration)})`);
	}

	console.log(`[COMPLETE] Total time: ${formatDuration(totalDuration)}`);

	return {
		success: !!state.data.finalDocument,
		finalDocument: state.data.finalDocument,
		state: state.data,
		timings: state.data.timings,
		totalDuration,
	};
}
